beatrix: Fix port of TestSubscription#testChangePlanWithStartDate from master
The test would create an Account with refTime = `2015-08-01T00:00:00.000Z`, then create a subscription using `null` dates, leading a subscription startDate of `2015-08-01T00:02:00.000Z`. Then, the changePlan would specify a LocalDate=`2015-08-01` which gets converted using account reference time to `2015-08-01T00:00:00.000Z`
and this leads to the exception :

```
Error:  Tests run: 342, Failures: 1, Errors: 0, Skipped: 215, Time elapsed: 655.152 s <<< FAILURE! - in TestSuite
Error:  org.killbill.billing.beatrix.integration.TestSubscription.testChangePlanWithStartDate  Time elapsed: 1.224 s  <<< FAILURE!
{cause=null, code=1021, formattedMsg='Subscription 8b19cf76-d1c7-45b6-a80b-49f7ab1488c7 is in state ACTIVE: Failed to change plan'}
	at org.killbill.billing.entitlement.api.DefaultEntitlement$6.doCall(DefaultEntitlement.java:719)
	at org.killbill.billing.entitlement.api.DefaultEntitlement$6.doCall(DefaultEntitlement.java:714)
	at org.killbill.billing.entitlement.api.EntitlementPluginExecution.executeWithPlugin(EntitlementPluginExecution.java:97)
	at org.killbill.billing.entitlement.api.DefaultEntitlement.changePlanWithDate(DefaultEntitlement.java:757)
	at org.killbill.billing.entitlement.api.DefaultEntitlement.changePlanWithDate(DefaultEntitlement.java:683)
```