util: add missing exports from the system bundle
This is to make all Felix bundles start.

The web console seems now to be fully functional even though we still
have the following error on startup:

ERROR: Bundle org.apache.felix.framework [0] EventDispatcher: Error during dispatch. (java.lang.ClassCastException: org.apache.felix.cm.impl.ConfigurationAdminImpl cannot be cast to org.osgi.service.cm.ConfigurationAdmin)
java.lang.ClassCastException: org.apache.felix.cm.impl.ConfigurationAdminImpl cannot be cast to org.osgi.service.cm.ConfigurationAdmin
  at org.apache.felix.fileinstall.internal.FileInstall$ConfigAdminSupport$Tracker.addingService(FileInstall.java:432)

Signed-off-by: Pierre-Alexandre Meyer <pierre@ning.com>